### ISSUE TITLE
Theme Activation Redirect

### ISSUE THREAD

**Issue by sakinshrestha** [codemonkey-jack/maera#164]
* If you are submitting theme in WordPress.org, theme should not redirect to any other page after activation. Currently, it redirects to theme_options page on activation.

**Comment by justintadlock** [comment]
Assuming you don't host with .ORG, you still need to check permissions before performing the redirect.  Make sure that `current_user_can( 'edit_theme_options' )` before doing the redirect.

**Comment by codemonkey-jack** [comment]
Good shout, added the check before the redirect.
