### ISSUE TITLE
Custom Logo Implementation

### ISSUE THREAD

**Issue by sakinshrestha** [codemonkey-jack/maera#168]
- As of WordPress 4.5, Custom Logo is inbuilt in WordPress code. Consider using that rather than implementing your custom logo. Ref: https://make.wordpress.org/core/2016/03/10/custom-logo/

**Comment by justintadlock** [comment]
Just noting that this is required for WP 4.5+ installs in the .ORG repo.  Custom methods are only allowed for back-compat.
