### ISSUE TITLE
Kirki Framework

### ISSUE THREAD

**Issue by sakinshrestha** [codemonkey-jack/maera#174]
* This theme is itself a framework and it is implementing Kirki Framework as well. Rather than using another framework, it will be better to implement Customizer API
Ref: https://developer.wordpress.org/themes/advanced-topics/customizer-api/

**Comment by justintadlock** [comment]
I'm not seeing anything from Kirki that you need in particular for this theme.  With a quick look at the customizer, is the theme even using Kirki for anything?

**Comment by codemonkey-jack** [comment]
Kirki is being used primarily for extensions shells that extend the framework. Have dropped Kirki from being required for the core framework and will instead require it as needed in additional add-ons.
