### ISSUE TITLE
Textdomain issues

### ISSUE THREAD

**Issue by sakinshrestha** [codemonkey-jack/maera#175]
- Themes should use one unique themeslug as text domain. In this case `maera`
- Currently, theme uses several text domains like: `maera_edd`, `edd`, `themename`, `maera`, `textdomain`, `maera_md`, `kirki`, `translation_domain`, `woocommerce`
- If it uses a framework then no more than 2 unique slugs

**Comment by justintadlock** [comment]
Additionally, the framework would also need to do something like in the following Gist in order to be allowed on .ORG (in order to work with the translation system): https://gist.github.com/justintadlock/7a605c29ae26c80878d0
