### ISSUE TITLE
Translation function issues

### ISSUE THREAD

**Issue by sakinshrestha** [codemonkey-jack/maera#176]
- In `maera/includes/admin/tabs/settings.php` lines 42 and 62, you have used `esc_attr_e()` without text domain. Further, you have added variable as its parameter
- Simply use `echo esc_attr()` only here as `esc_attr_e()` is a shorthand or `esc_attr()` and `_e()` function. You do not need `_e()` functionality here
- `_x()` used in `maera/includes/plugins/timber-library/lib/timber-helper.php` line 187 must have textdomain as third parameter
- In `maera/includes/widgets/extended-posts/class-Maera_Ext_Posts_Widget_Latest_Articles.php` line 22, you have passed classname in translation function, are you sure you want to do this? If translator changes the class, then any css/javascript with reference to that class will fail
- Make string in `maera/views/searchform.twig` line 4 and 5 `Search for:` translatable
- Textdomain missing on following:  
  - `maera/includes/class-maera-admin.php` line 190 and 200
  - `maera/includes/plugins/timber-library/lib/timber-helper.php` line 494 and 495
  - `maera/includes/plugins/timber-library/lib/timber-url-helper.php` line 259
  - `maera/includes/plugins/timber-library/lib/timber-url-helper.php` line 264
  - `maera/includes/plugins/timber-library/lib/timber-archives.php` lines 96 and 98
  - Please check thoroughly, there might be others as well
- Translation function calls must NOT contain PHP variables.
  - variable `$text` found in translation function in `includes/plugins/timber-library/lib/timber-twig.php` line 140
- `maera/includes/admin/tabs/docs/templating.php` all text needs to be translation ready

**Comment by justintadlock** [comment]
In `includes/class-maera-admin.php`, you're the "Theme Options" text is not internationalized (twice) on line 45:

```
add_theme_page( 'Theme Options', 'Theme Options', 'edit_theme_options', 'theme_options', array( $this, 'admin_page' ) );
```

**Comment by justintadlock** [comment]
In `includes/class-maera-widget-dropdown-class.php` on line 93, an empty string can't be translated:

	<option value="-1"><?php _e( '', 'maera_md' ); ?></option>

Just leave it empty:

	<option value="-1"></option>
