### ISSUE TITLE
eval() found

### ISSUE THREAD

**Issue by sakinshrestha** [codemonkey-jack/maera#177]
* `eval()` is not allowed and must not be used for following reasons
    * Potential unsafe input. Passing an untrusted parameter is a way to fail. It is often not a trivial task to make sure that a parameter (or part of it) is fully trusted
    * Trickiness. Using `eval()` makes code clever, therefore more difficult to follow and debug
    * Inexperienced developers who use it without enough consideration can be huge problem
* Found `eval` in the file `includes/plugins/timber-library/vendor/twig/twig/lib/Twig/Test/IntegrationTestCase.php`
    * Line 69: `eval('$ret = '.$condition.';');`
    * Line 81: ), `$match[2] ? eval($match[2].';') : array());`
    * Line 107: `$output = trim($template->render(eval($match[1].';')), '\n ');`
* `includes/plugins/timber-library/vendor/twig/twig/lib/Twig/Environment.php` line 332

**Comment by justintadlock** [comment]
Related to my comment on #188, any frameworks/libraries included with the theme would have to pass all the guidelines and the WordPress.org Theme Check.  `eval()` definitely wouldn't be allowed in a theme on .ORG.

**Comment by codemonkey-jack** [comment]
Notes: See comments on https://github.com/codemonkey-jack/maera/issues/188
