### ISSUE TITLE
Use WP_Filesystem methods

### ISSUE THREAD

**Issue by sakinshrestha** [codemonkey-jack/maera#178]
* Instead of `file_put_contents`, `file_get_contents`, etc, `WP_Filesystem` methods should be used
* Ref: https://codex.wordpress.org/Filesystem_API
* Check following:
    * `includes/plugins/timber-library/vendor/twig/twig/test/Twig/Tests/EnvironmentTest.php` line 50
    * `includes/plugins/timber-library/vendor/twig/twig/lib/Twig/Environment.php` line 1281
    * `includes/plugins/timber-library/vendor/twig/twig/lib/Twig/Test/IntegrationTestCase.php` line 41
    * `includes/plugins/timber-library/vendor/twig/twig/lib/Twig/Loader/Filesystem.php` line 130
    * `includes/plugins/timber-library/lib/timber-image-helper.php` line 282

**Comment by codemonkey-jack** [comment]
All come from the Timber plugin which is no longer embedded.
