### ISSUE TITLE
Use *_url() template tags, rather than bloginfo() equivalents

### ISSUE THREAD

**Issue by sakinshrestha** [codemonkey-jack/maera#183]
- `get_bloginfo('url')` was found in following files. Use `home_url( '/' )` instead
  - `includes/plugins/timber-library/vendor/upstatement/routes/Routes.php`. `Use home_url()` instead line 53
  - `includes/plugins/timber-library/lib/timber-site.php` lines 51 and 69
    *`includes/plugins/timber-library/lib/timber-site.php`
- Make sure you escape `home_url( '/' )` using`esc_url()` it you are using it for output

**Comment by codemonkey-jack** [comment]
Closing - From bundled plugin (Timber) which is no longer bundled.
