### ISSUE TITLE
Escaping/Sanitization issues

### ISSUE THREAD

**Issue by sakinshrestha** [codemonkey-jack/maera#186]
- Need to escape following using `esc_url()` before output
  - `maera/core-shell/views/pagination.twig`
    - line 4 pagination.prev.link
    - line 10 page.link
    - line 18 pagination.next.link
  - `maera/edd_templates/widget-cart-checkout.php` line 3 `edd_get_checkout_uri()`
    *`maera/edd_templates/widget-cart-item.php` line 4 `remove_url`
  - `maera/includes/class-maera-admin.php`
    - line 84 `"?page=theme_options&tab=' . $tab . '"`
    - line 191 and 201 `admin_url`
  - `maera/includes/plugins/timber-library/lib/timber-post.php` line 253 `$this->get_permalink()`
  - `maera/includes/plugins/timber-library/vendor/twig/twig/doc/templates.rst` line 31 `item.href`
  - There are several instances of `post.link` used without being escaped as follows. Check other instances of post.link too
    - `maera/views/content-entry-content.twig` line 3 `post.link`
    - `maera/views/content-entry-header.twig` line 4 `post.link`
    - `maera/views/content-single-entry-meta.twig` line 12 `category.get_path` and line 14 `post.link`
    - `maera/views/edd/content-download-content.twig` line 8 `post.link`
    - `maera/views/edd/content-download-header.twig` line 4 `post.link`
  - `maera/views/pagination.twig`
    - line 4 `pagination.prev.link`
    - line 10 `page.link`
    - line 18 `pagination.next.link`
  - `maera/views/site-logo.twig`
    - line 1 `site.url`
    - line 3 `TimberImage(site_logo.id).src` image source
  - `maera/views/woocommerce/single-product/add-to-cart/button-external.twig` line 1 `product_url`
  - `maera/woocommerce/single-product/add-to-cart/grouped.php` line 48 `get_permalink()`
  - `maera/views/content-entry-content.twig` line 4 `"{{ post.thumbnail.src|resize(thumbnail.width, thumbnail.height) }}"` and `"{{ post.thumbnail.src|resize(thumbnail.width, thumbnail.height)|retina(1) }} 1x, {{ post.thumbnail.src|resize(thumbnail.width, thumbnail.height)|retina(2) }}  2x"`
  - `maera/views/edd/content-download-header.twig` line 5 `"{{ post.thumbnail.src|resize( width, height ) }}"`, line 6 `"{{ default_image.src|resize( width, height, 'center' ) }}"`
  - `maera/views/edd/shortcode-download-content-grid.twig` line 25`"{{ post.thumbnail.src|resize( width, height ) }}"`, line 26 `"{{ default_image.src|resize( width, height, 'center' ) }}"`
  - `maera/views/edd/shortcode-download-content-list.twig` line 9 and 11 image sources
  - `maera/views/edd/shortcode-download-content-zoe.twig` line 6 and 7 image sources
  - `maera/views/edd/shortcode-download-image.twig` line 5 and 7 image sources
  - `maera/views/widget-extended-posts.twig` line 17 image source
- Need to use esc_attr() on following:
  - `maera/includes/admin/tabs/docs.php` line 20 `$docs_tab`
  - There are several instances of post.lititlenk used without being escaped as follows. Check others too
    - `maera/views/content-entry-content.twig` line 3 post.title (ignore this if post.title gets value from the_title_attribute() function )
    - `wp-content/themes/maera/views/content-entry-header.twig` line 4 `post.title`
    - `maera/views/edd/content-download-content.twig` line 8 `post.title`

**Comment by justintadlock** [comment]
In `includes/class-maera-widget-dropdown-class.php` on line 96, make sure to escape `$choice` (`esc_attr()`) and `$options['label']` (`esc_html()`).

	<option value="<?php echo $choice; ?>"<?php echo $selected; ?>><?php echo $options['label']; ?></option>

Also, use the core WP `selected()` function for outputting `selected="selected"`: https://codex.wordpress.org/Function_Reference/selected
