### ISSUE TITLE
Plugin Included

### ISSUE THREAD

**Issue by sakinshrestha** [codemonkey-jack/maera#188]
* Theme must not include plugin. A theme can recommend plugins but not include those plugins in the theme code.
* Check `maera/includes/plugins/timber-library`

**Comment by justintadlock** [comment]
Note that I'd say this is OK because this actually a framework/library.  It'd also be necessary to do if the Timber Library is required for the theme to function because core WP doesn't have a dependency system.  I'm just getting into the review though and will follow up if necessary.

**Comment by codemonkey-jack** [comment]
Required plugins have been removed. While it's still not optimal of course to require a plugin in this instance that is needed. But they've been removed as embedded plugins which keeps things cleaner and resolves some odd glitches with Timber not being detected as already active, resulting in a loop.
