### ISSUE TITLE
Wrong function for loading function files

### ISSUE THREAD

**Issue by justintadlock** [codemonkey-jack/maera#194]
The `locate_template()` function is for locating a template in a child theme (if it exists) and falling back to the parent theme.  It shouldn't be used for loading functions-style files.

From `functions.php`:

        require_once( locate_template( '/includes/template-hierarchy.php' ) );
        require_once( locate_template( '/includes/utils.php' ) );
        require_once( locate_template( '/includes/widgets.php' ) );

Instead, load files like so:

        require_once( get_template_directory() . '/includes/yourfilename.php' );

**Comment by justintadlock** [comment]
Note that I also noticed this issue in `includes/class-maera-init.php` too:

        require_once locate_template( '/includes/widgets/extended-posts/extended-posts.php' );

	require_once locate_template( '/includes/widgets/logo/logo.php' );

Make sure to clean up any other of the same issues throughout the theme.

**Comment by codemonkey-jack** [comment]
Fixed.
