### ISSUE TITLE
Required plugins

### ISSUE THREAD

**Issue by justintadlock** [codemonkey-jack/maera#209]
Most of the `Maera_Required_Plugins` class wouldn't be allowed on .ORG for the following reasons:

* Plugins can be recommended but not required.
* Admin notice should only be shown to a user with the `activate_plugins` capability.
* Themes cannot auto-activate or auto-deactivate plugins.

Aside from .ORG rules, themes should never auto-activate or auto-deactivate any plugins.

**Comment by codemonkey-jack** [comment]
Updated and removed auto activation of plugins. As this is a framework there aren't many alternatives to requiring those plugins as they are part of the framework and it won't function without them.
