### ISSUE TITLE
Broken search form filter

### ISSUE THREAD

**Issue by justintadlock** [codemonkey-jack/maera#210]
This filter on `get_search_form` breaks plugins that filter the search form:

        function get_search_form( $form ) {
		$form = '';
		locate_template( '/searchform.php', true, false );
		return $form;
	}

Because you're force-loading the `searchform.php` template, any plugin filtering this will cause a second search form to appear instead of overwriting the theme's search form.

**Comment by codemonkey-jack** [comment]
Fixed - This was actually also causing issues with the search widget, resulting in an internal server error. The offending files have been removed with core functionality now working as expected.
