### ISSUE TITLE
Twig + Timber on .ORG

### ISSUE THREAD

**Issue by justintadlock** [codemonkey-jack/maera#213]
You asked that I provided my opinion on whether such a theme would be allowed on the theme directory.  

Themes on .ORG are not allowed to require a plugin.  Therefore, your theme would have to work with the Timber Library plugin inactive.

And, inclusion of the plugin/library within the theme is probably going to be a non-starter based on the following issues alone.

* https://github.com/codemonkey-jack/maera/issues/178
* https://github.com/codemonkey-jack/maera/issues/177

Those are simply going to be a blocker, and I don't think you'll be able to make a case for them being an exception to the rule.  The TRT would require that the included plugin code follow all of the existing theme guidelines.  So, the only way to make that happen is to directly edit the included code to bring it up to TRT standards.  Of course, that's probably not a desirable route to take.

**Comment by codemonkey-jack** [comment]
Agreed. Going to close this out.
