### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by pinceladasdaweb** [codemonkey-jack/maera#217]
Few old PRs open, lots of Issues. If you're not interested in maintaining it, do you care to add someone as a maintainer?

Not trying to whine/demand, just curious.

**Comment by codemonkey-jack** [comment]
Hey @pinceladasdaweb,

Sorry just seen this, yep, 2.0 is being worked on which has sweeping changes across the board, so isn't currently in a public repo but will be when it's ready.

Primarily 2.0 focuses on removing plugin dependencies, re-writing all core Customizer code (removing Kirki), additional shell functionality and a bunch of bug fixes.
