### ISSUE TITLE
any update ?

### ISSUE THREAD

**Issue by raykai** [codemonkey-jack/maera#218]
so will there be any updates?

**Comment by codemonkey-jack** [comment]
Hey @raykai, 

Sorry just seen this, yep, 2.0 is being worked on which has sweeping changes across the board, so isn't currently in a public repo but will be when it's ready. 

Primarily 2.0 focuses on removing plugin dependencies, re-writing all core Customizer code (removing Kirki), additional shell functionality and a bunch of bug fixes.
